Fix pre-commit action failures: switch to ruby/setup-ruby
Fixes pre-commit errors of the form:
```
Run actions/setup-ruby@v1
  with:
    ruby-version: 2.6
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.13/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib
    ImageOS: ubuntu20
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
Error: Version 2.6 not found
```

While we're upgrading this pre-commit, also upgrade from ruby 2.6 to ruby 2.7.