fixed localhost address for macOS
I cannot start the training because i get this error:
File "/Users/user/Documents/ml-agents/ml-agents/mlagents/envs/rpc_communicator.py", line 70, in check_port
    s.bind(("localhost", port))
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

Using socket.gethostname() instead the training starts properly
I think that the error is linked to the fact that macOS use 0.0.0.0 instead of 127.0.0.0